sonar.projectKey=mashbot
sonar.projectName=mashbot
sonar.host.url=http://localhost:9000
sonar.sourceEncoding=UTF-8
sonar.sources=backend/app,frontend/src
sonar.tests=backend/tests
sonar.exclusions=**/__pycache__/**,**/node_modules/**,**/dist/**,**/alembic/versions/**
sonar.test.inclusions=backend/tests/**/*.py
sonar.python.version=3.12
sonar.login=squ_d55d8c89c5946fc0c5688f61ce4c2453fae25d79