import { useEffect, useState } from "react";
import { authHeaders, request } from "../api";

export default function DashboardPage({ token, onError, onNavigate }) {
  const [summary, setSummary] = useState(null);
  useEffect(() => { request("/dashboard/summary", { headers: authHeaders(token) }).then(setSummary).catch((err) => onError(err.message)); }, [token]);
  if (!summary) return <div className="loading-card">Loading your campaign pulse...</div>;
  const stats = [["Total campaigns", summary.total_campaigns, "all"], ["Needs approval", summary.pending_approval, "pending"], ["Scheduled", summary.scheduled_campaigns, "scheduled"], ["Connected services", summary.connected_services, "services"]];
  return <div className="page-stack"><section className="welcome-row"><div><p className="eyebrow orange">GOOD TO SEE YOU</p><h2>Your campaign pulse</h2><p className="muted">A quick read on what is moving through your workspace.</p></div><button onClick={() => onNavigate("create")}>+ New campaign</button></section><section className="stats-grid">{stats.map(([label, value, tone]) => <article className={`stat-card ${tone}`} key={label}><span>{label}</span><strong>{value}</strong><small>{tone === "pending" ? "Awaiting an approver" : tone === "scheduled" ? "Ready for launch" : "Across your workspace"}</small></article>)}</section><section className="dashboard-grid"><article className="panel dark-panel"><div className="panel-heading"><div><p className="eyebrow">CAMPAIGN PIPELINE</p><h2>At a glance</h2></div><span className="pulse-ring" /></div><div className="pipeline"><div><strong>{summary.draft_campaigns}</strong><span>Drafts</span></div><div><strong>{summary.pending_approval}</strong><span>Submitted</span></div><div><strong>{summary.scheduled_campaigns}</strong><span>Scheduled</span></div><div><strong>{summary.published_campaigns}</strong><span>Published</span></div></div></article><article className="panel"><div className="panel-heading"><div><p className="eyebrow orange">UP NEXT</p><h2>Upcoming schedule</h2></div><button className="text-button" onClick={() => onNavigate("schedule")}>View all →</button></div>{summary.upcoming.length === 0 ? <div className="empty-state"><span>◷</span><p>Nothing scheduled yet.</p><button className="secondary" onClick={() => onNavigate("schedule")}>Open schedule</button></div> : <div className="upcoming-list">{summary.upcoming.map((item) => <div className="upcoming-item" key={item.id}><div className="date-chip"><strong>{new Date(item.scheduled_for).getDate()}</strong><small>{new Date(item.scheduled_for).toLocaleString([], { month: "short" })}</small></div><div><strong>{item.name}</strong><p>{new Date(item.scheduled_for).toLocaleString([], { hour: "numeric", minute: "2-digit" })}</p></div><span className="status scheduled">scheduled</span></div>)}</div>}</article></section></div>;
}

