import { useEffect, useState } from "react";
import { authHeaders, request } from "../api";

export default function ExplorePage({ token, onMessage, onError }) {
  const [alerts, setAlerts] = useState([]);
  const [keyword, setKeyword] = useState("");
  const [provider, setProvider] = useState("all");
  useEffect(() => { request("/explore/alerts", { headers: authHeaders(token) }).then(setAlerts).catch((err) => onError(err.message)); }, [token]);
  async function addAlert(event) { event.preventDefault(); try { const alert = await request("/explore/alerts", { method: "POST", headers: authHeaders(token), body: JSON.stringify({ keyword, provider }) }); setAlerts([alert, ...alerts]); setKeyword(""); onMessage("Keyword alert created."); } catch (err) { onError(err.message); } }
  async function toggle(id) { try { const changed = await request(`/explore/alerts/${id}`, { method: "PATCH", headers: authHeaders(token) }); setAlerts(alerts.map((alert) => alert.id === id ? changed : alert)); } catch (err) { onError(err.message); } }
  return <div className="page-stack"><section className="split-heading"><div><p className="eyebrow orange">LISTENING POST</p><h2>Explore the conversation</h2><p className="muted">Keep a watchlist of topics that matter to your campaigns.</p></div><span className="explore-orbit">⌁</span></section><div className="explore-grid"><section className="panel alert-builder"><div className="section-number">01</div><h2>New keyword alert</h2><p className="muted">Create a monitored search for a connected service.</p><form onSubmit={addAlert}><label>Keyword or phrase<input value={keyword} onChange={(event) => setKeyword(event.target.value)} placeholder="e.g. sustainable packaging" required /></label><label>Service<select value={provider} onChange={(event) => setProvider(event.target.value)}><option value="all">All connected services</option><option value="twitter">Twitter</option><option value="facebook">Facebook</option><option value="blog">Blog</option></select></label><button>Create alert</button></form></section><section className="panel"><div className="panel-heading"><div><p className="eyebrow orange">YOUR WATCHLIST</p><h2>Active signals</h2></div><span className="count">{alerts.filter((alert) => alert.is_active).length}</span></div>{alerts.length === 0 ? <div className="empty-state"><span>⌁</span><p>No topics are being monitored yet.</p></div> : <div className="alert-list">{alerts.map((alert) => <div className={alert.is_active ? "alert-row" : "alert-row muted-row"} key={alert.id}><div className="alert-pulse" /><div><strong>{alert.keyword}</strong><small>{alert.provider} · {alert.is_active ? "Monitoring" : "Paused"}</small></div><button className="text-button" onClick={() => toggle(alert.id)}>{alert.is_active ? "Pause" : "Resume"}</button></div>)}</div>}</section></div><section className="panel explore-note"><span className="note-icon">i</span><div><h3>Provider data boundary</h3><p>Keyword alerts are stored in Mashbot and ready for provider-specific search adapters. Live external-service results will appear here when a real provider integration is configured.</p></div></section></div>;
}

