import { useEffect, useState } from "react";
import { authHeaders, request } from "../api";

export default function SchedulePage({ token, user, campaigns, onMessage, onError, refresh }) {
  const [scheduled, setScheduled] = useState([]);
  const [date, setDate] = useState("");
  useEffect(() => { request("/schedule", { headers: authHeaders(token) }).then(setScheduled).catch((err) => onError(err.message)); }, [token, campaigns]);
  async function schedule(id) { if (!date) return onError("Choose a future date and time first."); try { await request(`/campaigns/${id}/schedule`, { method: "POST", headers: authHeaders(token), body: JSON.stringify({ scheduled_for: new Date(date).toISOString() }) }); onMessage("Campaign scheduled."); setDate(""); refresh(); } catch (err) { onError(err.message); } }
  const ready = campaigns.filter((campaign) => campaign.status === "approved");
  return <div className="page-stack"><section className="split-heading"><div><p className="eyebrow orange">LAUNCH CALENDAR</p><h2>Schedule the moment</h2><p className="muted">Only approved content can move onto the publishing calendar.</p></div><label className="date-picker">Choose launch time<input type="datetime-local" value={date} onChange={(event) => setDate(event.target.value)} /></label></section><div className="schedule-grid"><section className="panel"><div className="panel-heading"><div><p className="eyebrow orange">READY TO GO</p><h2>Approved campaigns</h2></div><span className="count">{ready.length}</span></div>{ready.length === 0 ? <div className="empty-state"><span>◷</span><p>No approved campaigns are waiting for a launch time.</p><small>Submit a draft and have an approver review it first.</small></div> : ready.map((campaign) => <div className="ready-row" key={campaign.id}><div><strong>{campaign.name}</strong><p>{campaign.content}</p></div><button disabled={user.role !== "publisher" && user.role !== "admin"} onClick={() => schedule(campaign.id)}>Schedule</button></div>)}</section><section className="panel"><div className="panel-heading"><div><p className="eyebrow orange">CALENDAR FEED</p><h2>Upcoming</h2></div></div>{scheduled.length === 0 ? <div className="empty-state"><span>○</span><p>Your calendar is clear.</p></div> : <div className="calendar-feed">{scheduled.map((campaign) => <div className="calendar-item" key={campaign.id}><div className="calendar-date"><strong>{new Date(campaign.scheduled_for).getDate()}</strong><small>{new Date(campaign.scheduled_for).toLocaleString([], { month: "short" })}</small></div><div><strong>{campaign.name}</strong><p>{new Date(campaign.scheduled_for).toLocaleString()}</p></div><span className="status scheduled">{campaign.status}</span></div>)}</div>}</section></div></div>;
}

